// Per-skill conversion specs for the 45-skill corpus.
// Each gate carries BOTH forms so we can render naive vs improved from one source:
//   surface   = the lint/restatement a careless converter writes (what we score as the bug)
//   substance = the grounding-cross-checked gate authored to the improved bar
//   rule      = the verify.mjs rule the improved hard gate runs (proves it's non-vacuous)
//   redteam   = a one-line description of a plausible bad output the IMPROVED gate FAILS
// kind: 'hard' (mechanical, becomes a check:) | 'soft' (genuine judgment, a string gate)

const hard = (name, rule, redteam, surface, substance) => ({
  kind: "hard", name, rule, redteam, surface, substance,
});
const soft = (surface, substance) => ({ kind: "soft", surface, substance });

// Shorthand for a discover step that emits the list + grounding bundles.
const discover = (id, does, listAssert) => ({
  id,
  does,
  gate: [listAssert],
});

const finish = (id, does, coverage) => ({ does, gate: [coverage], id });

export const SPECS = [
  // ===================== 35 COMMON =====================
  {
    id: "data-migration", loop: true, listName: "tables", item: "table",
    intent: "Move rows from the legacy schema to the new schema with zero data loss and correct type mapping.",
    ground: "source row counts + per-row checksums vs the destination",
    discover: discover("scope-tables",
      "List every legacy table to migrate. For each, snapshot source row count + a checksum of\nkey columns into fixtures/<id>/<table>.ground.json — the truth the migration is checked against.",
      hard("Source snapshot captured for every table", "rowcount-match",
        "a table list with no source counts (so completeness can never be verified later)",
        "Every table in the list has a source row-count + checksum snapshot on disk",
        "Every table in the list has a source row-count + checksum snapshot on disk")),
    steps: [
      { id: "migrate-table", does: "Migrate <table>'s rows into the new schema, mapping each column type explicitly.",
        gate: [
          hard("Destination row count equals source (zero loss)", "rowcount-match",
            "migration that silently drops 4% of rows but writes the table",
            "Migrated table file exists",
            "Destination row count == source row count AND key-column checksum matches the source snapshot"),
          hard("No NULLs introduced in NOT-NULL columns", "no-new-nulls",
            "type-cast that turned unparseable values into NULL in a required column",
            "Migration ran",
            "No required column gained NULLs that the source row didn't have"),
          soft("Type mapping looks reasonable.",
            "Each type mapping is lossless for this table's real value range (e.g. no int overflow, no datetime-zone drift) — spot-checked against sampled source rows."),
        ]},
    ],
    finish: finish("scope-tables", "Confirm every table migrated with matching counts; produce a per-table loss report (must be 0 lost rows).",
      hard("Zero rows lost across all tables", "coverage-complete",
        "a run that migrated 9 of 12 tables and reported success",
        "A migration report exists",
        "Every scoped table has a destination==source verdict; total lost rows == 0")),
  },
  {
    id: "content-rewrite", loop: true, listName: "articles", item: "article",
    intent: "Rewrite each article for clarity while preserving every factual claim and all internal links.",
    ground: "the original article's extracted facts + link set",
    discover: discover("collect-articles",
      "Collect the articles to rewrite. For each, extract its factual claims and the set of internal links\ninto the grounding bundle — the rewrite must preserve these.",
      hard("Original facts + links extracted for each article", "links-preserved",
        "an article list with no extracted facts (so preservation can't be checked)",
        "Each article has an extracted facts+links grounding bundle",
        "Each article has an extracted facts+links grounding bundle")),
    steps: [
      { id: "rewrite-article", does: "Rewrite <article> for clarity.",
        gate: [
          hard("Every original internal link still present", "links-preserved",
            "a rewrite that dropped 3 of the original internal links",
            "Rewritten article file exists and is non-empty",
            "Every internal link in the original appears in the rewrite (no silent link loss)"),
          hard("No factual claim was added or contradicted", "facts-preserved",
            "a rewrite that invented a statistic absent from the original",
            "Rewrite parses as markdown",
            "Every claim in the rewrite is supported by the original's extracted facts; none contradicts them (grounding, not novelty: a reworded claim is fine, an invented number reds)"),
          soft("Reads more clearly.",
            "Reads measurably clearer to a layperson AND an expert wouldn't object to any rephrasing as having changed the meaning."),
        ]},
    ],
    finish: finish("collect-articles", "Confirm every article rewritten with links+facts preserved.",
      hard("All articles covered, none lost facts/links", "coverage-complete",
        "skipping 2 articles in the batch",
        "A summary exists", "Every collected article has a preserved-links + preserved-facts verdict")),
  },
  {
    id: "research-synthesis", loop: true, listName: "subclaims", item: "claim",
    intent: "Synthesize a cited answer where every claim traces to a fetched source.",
    ground: "the fetched source texts",
    discover: discover("fetch-sources",
      "Decompose the question into sub-claims and fetch real sources for each into the grounding bundle\n(the source text every later citation must trace to).",
      hard("Real source text fetched per sub-claim", "source-backed",
        "sub-claims with citation URLs but no fetched body text (so 'backing' is unverifiable)",
        "A sub-claim list exists",
        "Each sub-claim has fetched source body text on disk (not just a URL)")),
    steps: [
      { id: "write-claim", does: "Write <claim>'s answer with its citation.",
        gate: [
          hard("Claim is supported by its cited source's actual text", "source-backed",
            "a claim whose cited source text does not mention the asserted fact",
            "The claim has a citation",
            "The claim's asserted fact appears in / is entailed by the fetched source text it cites (not just a plausible-looking URL)"),
          soft("Citation looks credible.",
            "The cited source is actually RELEVANT and authoritative for this specific claim (not a tangential page that merely contains the keyword)."),
        ]},
    ],
    finish: finish("fetch-sources", "Assemble the cited answer; confirm no uncited claim slipped in.",
      hard("Zero uncited claims in the final answer", "coverage-complete",
        "a synthesis paragraph containing a confident claim with no citation",
        "An answer document exists", "Every claim in the final answer maps to a fetched, on-disk source")),
  },
  {
    id: "code-review", loop: true, listName: "changed_files", item: "file",
    intent: "Find real defects in each changed file; every finding has a line + concrete fix that compiles.",
    ground: "the actual diff + a build/typecheck of the proposed fix",
    discover: discover("collect-diff",
      "List changed files from the diff; capture each file's actual changed-line ranges into the grounding\nbundle so findings can be checked to land on real changed lines.",
      hard("Real changed-line ranges captured per file", "lines-in-diff",
        "a file list with no line ranges (so a finding could cite a line that wasn't even touched)",
        "A changed-file list exists",
        "Each file has its real changed-line ranges on disk")),
    steps: [
      { id: "review-file", does: "Review <file> for real defects.",
        gate: [
          hard("Each finding cites a line that is actually in the diff", "lines-in-diff",
            "a finding citing line 412 when the diff only touched lines 10-30",
            "At least one finding was produced",
            "Every finding's cited line falls within this file's real changed-line ranges"),
          hard("Each proposed fix compiles / typechecks", "fix-compiles",
            "a suggested fix that references an undefined symbol and would not build",
            "Each finding has a suggested fix string",
            "Applying each proposed fix passes build/typecheck (a fix that breaks the build is worse than no fix)"),
          soft("Findings seem worthwhile.",
            "Findings are genuine defects (not style nits dressed as bugs); no real defect in the changed lines was missed."),
        ]},
    ],
    finish: finish("collect-diff", "Roll findings into one review with an overall verdict.",
      hard("Every changed file reviewed", "coverage-complete",
        "a review that silently skipped a changed file",
        "A review file exists", "Every file in the diff has a verdict")),
  },
  {
    id: "batch-api-sync", loop: true, listName: "records", item: "record",
    intent: "Sync each record to the remote API so remote state equals local intent, idempotently.",
    ground: "a read-back of remote state vs the local desired payload",
    discover: discover("load-records",
      "Load the records to sync. For each, snapshot the local DESIRED payload into the grounding bundle —\nthe target remote state to verify against after the push.",
      hard("Desired payload captured per record", "remote-matches",
        "a record list with no desired-state snapshot (so 'synced' can't be verified)",
        "A record list exists",
        "Each record has its desired-payload snapshot on disk")),
    steps: [
      { id: "sync-record", does: "Push <record> to the remote API.",
        gate: [
          hard("Remote read-back equals desired payload", "remote-matches",
            "a push that returned 200 but left the remote field stale (no read-back done)",
            "The push call returned a 2xx",
            "A fresh GET of the remote record equals the desired payload field-for-field (verify against the API, not the request you sent)"),
          hard("Re-running is idempotent (no duplicate created)", "idempotent",
            "a sync that creates a second remote row on retry instead of updating",
            "The sync completed",
            "Running the sync twice leaves exactly one remote record (idempotency key respected)"),
          soft("Looks synced.",
            "No partial/torn write: every field of the record reached the remote, not just the first few before a rate-limit."),
        ]},
    ],
    finish: finish("load-records", "Confirm remote state matches local intent for all records.",
      hard("All records reconciled", "coverage-complete",
        "reporting success while 30 records 429'd and were never retried",
        "A sync log exists", "Every loaded record has a remote-matches verdict")),
  },
  {
    id: "report-generation", loop: false,
    intent: "Generate a report whose every number traces to the underlying dataset query.",
    ground: "the dataset query results",
    steps: [
      { id: "run-queries", does: "Run the source queries and snapshot their results into the grounding bundle.",
        gate: [ hard("Query results snapshotted", "numbers-trace",
          "writing the report from memory without snapshotting the query outputs",
          "A results file exists",
          "Each metric the report will cite has a corresponding query-result value on disk") ]},
      { id: "write-report", does: "Write the report.",
        gate: [
          hard("Every figure in the report equals a query result", "numbers-trace",
            "a report headline of '+18% MoM' when the query result was +8%",
            "The report renders without errors",
            "Every number in the report matches a value in the snapshotted query results (no figure invented or rounded into a different story)"),
          soft("Narrative is clear.",
            "The narrative's causal claims are supported by the data, not just the headline numbers — no story the data doesn't tell."),
        ]},
    ],
  },
  {
    id: "web-scraping", loop: true, listName: "pages", item: "page",
    intent: "Extract structured records from each page; fields match what the live page actually shows.",
    ground: "the live page HTML",
    discover: discover("list-pages",
      "List target pages and fetch each page's raw HTML into the grounding bundle (the truth the\nextracted fields are checked against).",
      hard("Raw HTML captured per page", "fields-on-page",
        "a page list with no fetched HTML (so extracted fields can't be verified)",
        "A page list exists", "Each page has its fetched raw HTML on disk")),
    steps: [
      { id: "extract-page", does: "Extract structured fields from <page>.",
        gate: [
          hard("Every extracted value appears in the page HTML", "fields-on-page",
            "an extracted price of 499 that appears nowhere in the page (hallucinated/stale)",
            "Extraction produced a JSON record",
            "Every extracted field value is present in this page's fetched HTML (verify against the page, not a cached guess)"),
          soft("Extraction looks complete.",
            "No record on the page was missed and none is a duplicate of pagination/boilerplate."),
        ]},
    ],
    finish: finish("list-pages", "Confirm every page scraped, fields grounded in HTML.",
      hard("All pages covered", "coverage-complete",
        "stopping after page 3 of 40 and declaring done",
        "A results file exists", "Every listed page has an extracted-and-grounded record set")),
  },
  {
    id: "test-authoring", loop: true, listName: "targets", item: "target",
    intent: "Write tests that actually exercise the target code and fail when it regresses.",
    ground: "coverage of the target + a mutation/break check",
    discover: discover("pick-targets",
      "Pick the functions/modules to test; snapshot each target's signature + a known-good baseline into\nthe grounding bundle.",
      hard("Targets + baseline captured", "test-meaningful",
        "a target list with no baseline (so a vacuous assert-true test would pass review)",
        "A target list exists", "Each target has a baseline behaviour snapshot on disk")),
    steps: [
      { id: "write-test", does: "Write tests for <target>.",
        gate: [
          hard("Test fails when the target is broken (catches regression)", "test-meaningful",
            "an assert(true) test that passes no matter what the target does",
            "The test file exists and the suite is green",
            "Mutating/breaking the target makes this test FAIL (a green test that survives a broken target is worthless)"),
          hard("Test actually executes the target code", "covers-target",
            "a test that imports the module but never calls the target function",
            "The test runs",
            "Coverage shows the target's lines were executed by this test"),
          soft("Tests read well.",
            "Cases cover the real edge conditions (empty, boundary, error path), not just the happy path."),
        ]},
    ],
    finish: finish("pick-targets", "Confirm each target has a regression-catching test.",
      hard("All targets covered", "coverage-complete",
        "leaving 5 targets with no test",
        "A test report exists", "Every target has at least one test that fails on a break")),
  },
  {
    id: "refactor", loop: true, listName: "modules", item: "module",
    intent: "Restructure code without changing observable behavior; tests still green.",
    ground: "the pre-refactor test suite + public API surface",
    discover: discover("snapshot-behavior",
      "Snapshot the public API surface + a passing test run for each module into the grounding bundle\n(the behaviour the refactor must preserve).",
      hard("Behaviour baseline captured per module", "behavior-preserved",
        "starting to refactor with no green baseline recorded (can't prove behaviour preserved)",
        "A module list exists", "Each module has a passing-baseline + API snapshot on disk")),
    steps: [
      { id: "refactor-module", does: "Refactor <module>.",
        gate: [
          hard("Tests still pass after refactor (behaviour preserved)", "behavior-preserved",
            "a refactor that 'cleaned up' a branch and now 2 tests fail",
            "The module still compiles",
            "The same test suite that passed before still passes after (no behaviour change)"),
          hard("Public API surface unchanged (or change is intended+noted)", "api-stable",
            "a refactor that silently renamed an exported function callers depend on",
            "The file changed",
            "Exported symbols match the baseline API snapshot (no accidental breaking change)"),
          soft("Code is cleaner.",
            "The structure is genuinely simpler (less duplication/coupling), not just moved around."),
        ]},
    ],
    finish: finish("snapshot-behavior", "Confirm full suite green, no API drift.",
      hard("All modules behaviour-preserved", "coverage-complete",
        "declaring done while one module's tests are red",
        "A report exists", "Every module has a behaviour-preserved + api-stable verdict")),
  },
  {
    id: "deploy-pipeline", loop: false,
    intent: "Ship the build to prod only if health checks pass and rollback is proven.",
    ground: "the live health endpoint + the prior known-good version",
    steps: [
      { id: "record-baseline", does: "Record the current prod version + a passing health snapshot into the grounding bundle.",
        gate: [ hard("Rollback target recorded", "rollback-ready",
          "deploying with no recorded prior version to roll back to",
          "A baseline file exists", "The prior known-good version id + its health snapshot are on disk") ]},
      { id: "deploy", does: "Deploy the new build and verify health.",
        gate: [
          hard("Post-deploy health checks pass on the LIVE endpoint", "health-green",
            "a deploy marked success while /health returns 503",
            "The deploy command exited 0",
            "The live health endpoint returns green AFTER the deploy (verify the running service, not the CI log)"),
          hard("Rollback path is proven (can restore prior version)", "rollback-ready",
            "no rollback rehearsal, so a bad deploy can't be reverted",
            "A rollback script exists",
            "A dry-run restore of the recorded prior version succeeds"),
          soft("Deploy looks healthy.",
            "Key user-facing flows (not just /health) respond correctly post-deploy."),
        ]},
    ],
  },
  {
    id: "dataset-labeling", loop: true, listName: "items", item: "item",
    intent: "Label each item per the rubric; labels are valid and inter-consistent with the rubric.",
    ground: "the rubric (allowed labels + decision criteria) + the item content",
    discover: discover("load-rubric",
      "Load the labeling rubric (allowed label set + criteria) and the items into the grounding bundle.",
      hard("Rubric + items loaded", "label-valid",
        "labeling with no allowed-label set on disk (so any string passes)",
        "An item list exists", "The rubric's allowed-label set is on disk for every item")),
    steps: [
      { id: "label-item", does: "Label <item>.",
        gate: [
          hard("Label is in the rubric's allowed set", "label-valid",
            "a label 'maybe-ish' that isn't one of the rubric's classes",
            "A label was assigned",
            "The assigned label is one of the rubric's allowed labels"),
          hard("Label justification matches rubric criteria for that label", "label-grounded",
            "labeling an item 'spam' whose content meets none of the rubric's spam criteria",
            "A justification string exists",
            "The item's content satisfies the rubric criteria for the chosen label (label traces to the item, not a coin flip)"),
          soft("Labels look consistent.",
            "Borderline items are labeled consistently with similar items (no rubric drift across the batch)."),
        ]},
    ],
    finish: finish("load-rubric", "Confirm every item labeled with a valid, grounded label.",
      hard("All items labeled", "coverage-complete",
        "leaving 12 items unlabeled",
        "A label file exists", "Every item has a valid, justified label")),
  },
  {
    id: "email-triage", loop: true, listName: "emails", item: "email",
    intent: "Route each email to the right queue with a reason grounded in the email content.",
    ground: "the email body + the routing rules",
    discover: discover("ingest-emails",
      "Ingest the emails + the routing rules (queues + their trigger criteria) into the grounding bundle.",
      hard("Emails + routing rules loaded", "route-valid",
        "routing with no defined queue set (so any destination passes)",
        "An email list exists", "The queue set + rules are on disk")),
    steps: [
      { id: "route-email", does: "Route <email> to a queue.",
        gate: [
          hard("Destination queue is a real defined queue", "route-valid",
            "routing to a queue 'misc-stuff' that doesn't exist",
            "A queue was chosen",
            "The chosen queue is one of the defined queues"),
          hard("Routing reason cites content actually in the email", "route-grounded",
            "routing as 'refund request' when the email never mentions a refund",
            "A reason string exists",
            "The reason quotes/references text that actually appears in the email body"),
          soft("Routing seems right.",
            "Ambiguous emails went to the safest queue, not a confident wrong one."),
        ]},
    ],
    finish: finish("ingest-emails", "Confirm every email routed with a grounded reason.",
      hard("All emails triaged", "coverage-complete",
        "leaving 8 emails in the inbox untriaged",
        "A triage log exists", "Every email has a queue + grounded reason")),
  },
  {
    id: "log-analysis", loop: false,
    intent: "Identify the root-cause incident from logs; every claim cites a real log line.",
    ground: "the raw log lines",
    steps: [
      { id: "ingest-logs", does: "Ingest the raw logs into the grounding bundle (every line addressable).",
        gate: [ hard("Raw logs captured", "claims-cite-logs",
          "writing the postmortem from memory with no log file on disk",
          "A log file exists", "The raw log lines are on disk and line-addressable") ]},
      { id: "diagnose", does: "Write the root-cause analysis.",
        gate: [
          hard("Every claim cites a log line that actually exists", "claims-cite-logs",
            "a timeline claiming 'OOM at 14:02' when no such line exists in the logs",
            "An analysis document exists",
            "Every timestamp/error the analysis asserts maps to a real line in the raw logs"),
          soft("Root cause is convincing.",
            "The causal chain is the most likely explanation given the evidence, not the first plausible one."),
        ]},
    ],
  },
  {
    id: "image-classification", loop: true, listName: "images", item: "image",
    intent: "Assign each image a valid class with confidence; class is one the model supports.",
    ground: "the image + the allowed class set",
    discover: discover("load-images",
      "Load the images + the allowed class taxonomy into the grounding bundle.",
      hard("Images + taxonomy loaded", "class-valid",
        "classifying with no allowed-class set (so any label passes)",
        "An image list exists", "The allowed class set is on disk")),
    steps: [
      { id: "classify-image", does: "Classify <image>.",
        gate: [
          hard("Class is in the allowed taxonomy", "class-valid",
            "predicting 'spaceship' when it isn't a supported class",
            "A class was predicted",
            "The predicted class is in the allowed set"),
          hard("Confidence is a valid probability in [0,1]", "conf-valid",
            "a confidence of 1.7",
            "A confidence number exists",
            "Confidence is within [0,1]"),
          soft("Predictions look plausible.",
            "Low-confidence images were flagged for review rather than force-labeled."),
        ]},
    ],
    finish: finish("load-images", "Confirm every image classified with a valid class+confidence.",
      hard("All images classified", "coverage-complete",
        "skipping the corrupt-but-readable images",
        "A predictions file exists", "Every image has a valid class+confidence")),
  },
  {
    id: "invoice-processing", loop: true, listName: "invoices", item: "invoice",
    intent: "Extract invoice fields; totals reconcile (line items sum to total) and match the document.",
    ground: "the invoice document",
    discover: discover("load-invoices",
      "Load the invoice documents into the grounding bundle (the source the extracted fields are checked against).",
      hard("Invoice docs captured", "total-reconciles",
        "an invoice list with no source document text (extraction unverifiable)",
        "An invoice list exists", "Each invoice's source document is on disk")),
    steps: [
      { id: "extract-invoice", does: "Extract <invoice>'s fields.",
        gate: [
          hard("Line items sum to the stated total", "total-reconciles",
            "extracted line items summing to 940 while the total field says 1040",
            "Fields were extracted",
            "Sum of extracted line-item amounts equals the extracted total (internal consistency)"),
          hard("Extracted total matches the document", "total-on-doc",
            "an extracted total of 1040 when the document clearly shows 1400 (OCR transposition)",
            "A total was extracted",
            "The extracted total string appears in the source document"),
          soft("Extraction looks right.",
            "Currency, tax lines, and dates were read correctly (not just the headline total)."),
        ]},
    ],
    finish: finish("load-invoices", "Confirm every invoice extracted + reconciled.",
      hard("All invoices processed", "coverage-complete",
        "skipping the multi-page invoices",
        "A results file exists", "Every invoice has reconciled, document-matching fields")),
  },
  {
    id: "translation-pass", loop: true, listName: "segments", item: "segment",
    intent: "Translate each segment preserving meaning, numbers, and untranslatable terms.",
    ground: "the source segment",
    discover: discover("load-segments",
      "Load source segments + a glossary of do-not-translate terms into the grounding bundle.",
      hard("Source + glossary loaded", "nums-preserved",
        "a segment list with no source text (translation unverifiable)",
        "A segment list exists", "Each segment's source + the glossary are on disk")),
    steps: [
      { id: "translate-segment", does: "Translate <segment>.",
        gate: [
          hard("All numbers/units preserved exactly", "nums-preserved",
            "a translation that turned '3.5 mg' into '35 mg'",
            "A translation string exists",
            "Every number+unit in the source appears unchanged in the translation"),
          hard("Glossary do-not-translate terms left intact", "glossary-kept",
            "translating a brand name that the glossary marks do-not-translate",
            "Translation produced",
            "Every glossary-protected term appears verbatim in the translation"),
          soft("Reads naturally.",
            "Meaning preserved with natural target-language phrasing, not a literal word-for-word calque."),
        ]},
    ],
    finish: finish("load-segments", "Confirm every segment translated faithfully.",
      hard("All segments translated", "coverage-complete",
        "leaving placeholder source text in 5 segments",
        "An output file exists", "Every segment has a faithful translation")),
  },
  {
    id: "seo-audit", loop: true, listName: "pages", item: "page",
    intent: "Audit each page against SEO rules; findings reflect the page's real HTML/meta.",
    ground: "the live page (HTML + meta tags)",
    discover: discover("crawl-pages",
      "Crawl the pages; capture each page's real title/meta/headings into the grounding bundle.",
      hard("Page meta captured", "finding-on-page",
        "a page list with no captured meta (so a finding could be invented)",
        "A page list exists", "Each page's title+meta+headings are on disk")),
    steps: [
      { id: "audit-page", does: "Audit <page> against the SEO rules.",
        gate: [
          hard("Each finding reflects the page's real meta", "finding-on-page",
            "flagging 'title too long' on a page whose captured title is 48 chars",
            "Findings were produced",
            "Each finding's asserted value (title length, missing meta, etc.) matches the captured page meta"),
          soft("Recommendations are useful.",
            "Recommendations are prioritized by real impact, not a flat checklist dump."),
        ]},
    ],
    finish: finish("crawl-pages", "Confirm every page audited against real meta.",
      hard("All pages audited", "coverage-complete",
        "auditing 10 of 50 pages",
        "An audit file exists", "Every crawled page has grounded findings")),
  },
  {
    id: "dependency-upgrade", loop: true, listName: "deps", item: "dep",
    intent: "Upgrade each dependency without breaking the build or introducing known CVEs.",
    ground: "the lockfile + build + the advisory database",
    discover: discover("list-deps",
      "List deps to upgrade; snapshot current versions + a green build baseline into the grounding bundle.",
      hard("Baseline build + versions captured", "build-green-after",
        "upgrading with no green baseline (can't tell if the upgrade broke it)",
        "A dep list exists", "Current versions + a passing build baseline are on disk")),
    steps: [
      { id: "upgrade-dep", does: "Upgrade <dep>.",
        gate: [
          hard("Build still passes after upgrade", "build-green-after",
            "an upgrade that introduced a breaking API change and the build now fails",
            "The lockfile changed",
            "The build/test suite passes after the upgrade (no regression)"),
          hard("Upgraded version has no known CVE in the advisory DB", "no-known-cve",
            "pinning to a version with a published critical advisory",
            "A version was selected",
            "The chosen version is not flagged in the advisory database"),
          soft("Upgrade is sensible.",
            "Major-version jumps were reviewed for migration notes, not auto-bumped blindly."),
        ]},
    ],
    finish: finish("list-deps", "Confirm all deps upgraded, build green, no CVEs.",
      hard("All deps handled", "coverage-complete",
        "leaving 4 deps un-upgraded but reporting done",
        "A report exists", "Every dep has a build-green + no-CVE verdict")),
  },
  {
    id: "changelog-generation", loop: false,
    intent: "Generate a changelog where every entry maps to a real merged commit/PR.",
    ground: "the git log",
    steps: [
      { id: "collect-commits", does: "Collect the merged commits/PRs in range into the grounding bundle.",
        gate: [ hard("Commit range captured", "entry-maps-commit",
          "writing the changelog from memory with no commit list on disk",
          "A commit file exists", "The merged commits in range are on disk") ]},
      { id: "write-changelog", does: "Write the changelog.",
        gate: [
          hard("Every entry maps to a real commit/PR", "entry-maps-commit",
            "a changelog entry 'Added dark mode' with no commit that did so",
            "The changelog renders",
            "Every changelog entry references a commit/PR that exists in the collected range"),
          soft("Changelog is readable.",
            "Entries are grouped and worded for users, not raw commit subjects."),
        ]},
    ],
  },
  {
    id: "survey-analysis", loop: false,
    intent: "Summarize survey results; every stat recomputes from the raw responses.",
    ground: "the raw response CSV",
    steps: [
      { id: "load-responses", does: "Load the raw survey responses into the grounding bundle.",
        gate: [ hard("Raw responses captured", "stat-recomputes",
          "summarizing with no raw responses on disk",
          "A responses file exists", "The raw response rows are on disk") ]},
      { id: "summarize-survey", does: "Write the survey summary.",
        gate: [
          hard("Every reported stat recomputes from the raw data", "stat-recomputes",
            "claiming '72% satisfied' when recomputing the raw responses gives 61%",
            "A summary exists",
            "Every percentage/mean in the summary equals a recomputation from the raw responses (no eyeballed stat)"),
          soft("Insights are fair.",
            "Free-text themes reflect the actual distribution, not cherry-picked quotes."),
        ]},
    ],
  },
  {
    id: "pdf-data-extraction", loop: true, listName: "pdfs", item: "pdf",
    intent: "Extract a structured table from each PDF; cells match the source page.",
    ground: "the PDF page text",
    discover: discover("load-pdfs",
      "Load each PDF's extracted page text into the grounding bundle (cells are checked against it).",
      hard("PDF text captured", "cells-on-page",
        "a pdf list with no extracted page text (cells unverifiable)",
        "A pdf list exists", "Each PDF's page text is on disk")),
    steps: [
      { id: "extract-table", does: "Extract <pdf>'s table.",
        gate: [
          hard("Every non-derived cell appears in the page text", "cells-on-page",
            "a cell value '12,340' that appears nowhere on the source page",
            "A table was extracted",
            "Every extracted cell value (that isn't a computed total) is present in the PDF's page text"),
          soft("Table structure is right.",
            "Row/column alignment matches the document; merged cells handled, not flattened wrong."),
        ]},
    ],
    finish: finish("load-pdfs", "Confirm every PDF table extracted + grounded.",
      hard("All PDFs covered", "coverage-complete",
        "skipping scanned (image) PDFs silently",
        "A results file exists", "Every PDF has a grounded extracted table")),
  },
  {
    id: "accessibility-audit", loop: true, listName: "views", item: "view",
    intent: "Flag real a11y violations per WCAG on each view; each cites a DOM node.",
    ground: "the rendered DOM",
    discover: discover("render-views",
      "Render each view; capture its DOM snapshot into the grounding bundle.",
      hard("DOM snapshots captured", "violation-on-dom",
        "a view list with no DOM snapshot (so a violation could be invented)",
        "A view list exists", "Each view's DOM snapshot is on disk")),
    steps: [
      { id: "audit-view", does: "Audit <view> for WCAG violations.",
        gate: [
          hard("Each violation cites a node that exists in the DOM", "violation-on-dom",
            "flagging a missing alt on an <img> that doesn't exist in the snapshot",
            "Violations were listed",
            "Every violation references a selector/node present in the captured DOM"),
          soft("Audit is thorough.",
            "Real blockers (focus traps, contrast) are caught, not just trivially-automatable rules."),
        ]},
    ],
    finish: finish("render-views", "Confirm every view audited against its DOM.",
      hard("All views audited", "coverage-complete",
        "auditing the homepage and calling it done",
        "An audit file exists", "Every view has DOM-grounded findings")),
  },
  {
    id: "data-cleaning", loop: false,
    intent: "Clean a dataset: no nulls in required cols, dedup, valid types; row provenance kept.",
    ground: "the raw dataset",
    steps: [
      { id: "load-raw", does: "Load the raw dataset + its schema into the grounding bundle.",
        gate: [ hard("Raw dataset + schema captured", "clean-valid",
          "cleaning with no raw snapshot (can't prove no real rows were dropped)",
          "A raw file exists", "The raw dataset + required-column schema are on disk") ]},
      { id: "clean", does: "Clean the dataset.",
        gate: [
          hard("No nulls remain in required columns + types valid", "clean-valid",
            "a 'cleaned' file still containing nulls in a required column",
            "An output file exists",
            "Required columns have no nulls and all values match their declared types"),
          hard("No legitimate rows silently dropped (provenance)", "no-row-loss",
            "dedup that removed near-duplicates which were actually distinct records",
            "Cleaning ran",
            "Every dropped row is logged with a reason; non-duplicate rows are all retained"),
          soft("Cleaning is sound.",
            "Outlier/imputation choices are defensible, not silently lossy."),
        ]},
    ],
  },
  {
    id: "ab-test-readout", loop: false,
    intent: "Report A/B result with correct significance math from the raw event counts.",
    ground: "the raw event counts",
    steps: [
      { id: "load-counts", does: "Load raw per-variant event counts into the grounding bundle.",
        gate: [ hard("Raw counts captured", "stats-correct",
          "computing significance with no raw counts on disk",
          "A counts file exists", "Per-variant exposure + conversion counts are on disk") ]},
      { id: "readout", does: "Write the A/B readout.",
        gate: [
          hard("Significance + lift recompute correctly from the counts", "stats-correct",
            "declaring 'significant, p<0.05' when recomputing from counts gives p=0.21",
            "A readout exists",
            "The reported lift and p-value recompute correctly from the raw counts (no p-hacked or eyeballed verdict)"),
          soft("Interpretation is honest.",
            "Caveats (peeking, sample ratio mismatch, segment effects) are surfaced, not buried."),
        ]},
    ],
  },
  {
    id: "ticket-deduplication", loop: true, listName: "clusters", item: "cluster",
    intent: "Merge each duplicate ticket cluster; merged tickets are genuinely the same issue.",
    ground: "the ticket texts (similarity evidence)",
    discover: discover("cluster-tickets",
      "Group candidate duplicate tickets into clusters; capture each ticket's text into the grounding bundle.",
      hard("Ticket texts captured per cluster", "merge-justified",
        "clusters with no ticket text (so 'duplicate' can't be verified)",
        "A cluster list exists", "Each cluster's ticket texts are on disk")),
    steps: [
      { id: "merge-cluster", does: "Decide and merge <cluster>.",
        gate: [
          hard("Merged tickets share the actual same issue", "merge-justified",
            "merging a 'login fails' ticket with a 'billing wrong' ticket",
            "A merge happened",
            "The tickets in the merge share concrete evidence of the same issue (overlapping error/symptom), not just a shared keyword"),
          soft("Merge is safe.",
            "No distinct-but-similar tickets were merged; the surviving ticket keeps all linked context."),
        ]},
    ],
    finish: finish("cluster-tickets", "Confirm every cluster resolved with justified merges.",
      hard("All clusters handled", "coverage-complete",
        "leaving half the clusters unresolved",
        "A merge log exists", "Every cluster has a justified merge/keep-separate verdict")),
  },
  {
    id: "config-validation", loop: true, listName: "configs", item: "config",
    intent: "Validate each config file against schema + cross-file references resolve.",
    ground: "the schema + the referenced files",
    discover: discover("load-configs",
      "Load the config files + the schema + the referenceable target set into the grounding bundle.",
      hard("Configs + schema + targets loaded", "schema-valid",
        "validating with no schema on disk (so any shape passes)",
        "A config list exists", "The schema + reference targets are on disk")),
    steps: [
      { id: "validate-config", does: "Validate <config>.",
        gate: [
          hard("Config conforms to the schema", "schema-valid",
            "passing a config missing a required key the schema demands",
            "The file parses",
            "The config validates against the schema (required keys, types, enums)"),
          hard("Every cross-file reference resolves to a real target", "refs-resolve",
            "a config referencing a service 'auth-v2' that exists in no referenceable target",
            "References were listed",
            "Every referenced id resolves to a real target in the loaded set (no dangling reference)"),
          soft("Config is coherent.",
            "Values are mutually consistent (e.g. a timeout < a retry budget), not just individually valid."),
        ]},
    ],
    finish: finish("load-configs", "Confirm every config valid + references resolve.",
      hard("All configs validated", "coverage-complete",
        "validating 2 of 9 configs",
        "A report exists", "Every config has a schema + reference verdict")),
  },
  {
    id: "sql-optimization", loop: true, listName: "queries", item: "query",
    intent: "Rewrite each slow query to be faster with an identical result set.",
    ground: "the EXPLAIN plan + result-set equality vs the original",
    discover: discover("profile-queries",
      "Profile each slow query; snapshot its result-set + baseline cost into the grounding bundle.",
      hard("Result-set + cost baseline captured", "result-equal",
        "rewriting with no baseline result-set (can't prove equivalence)",
        "A query list exists", "Each query's result-set + baseline cost are on disk")),
    steps: [
      { id: "rewrite-query", does: "Rewrite <query>.",
        gate: [
          hard("Rewritten query returns the identical result set", "result-equal",
            "a rewrite that changed a LEFT to INNER join and now returns fewer rows",
            "The new query runs",
            "The rewrite's result-set equals the baseline result-set exactly (faster is useless if wrong)"),
          hard("Rewritten query is actually cheaper", "cheaper-plan",
            "a 'rewrite' whose EXPLAIN cost is higher than the original",
            "An EXPLAIN was produced",
            "The rewrite's estimated cost is lower than the baseline"),
          soft("Rewrite is maintainable.",
            "The faster query is still readable, not an unmaintainable hint-soup."),
        ]},
    ],
    finish: finish("profile-queries", "Confirm every query faster + result-equal.",
      hard("All queries handled", "coverage-complete",
        "optimizing the easy queries, skipping the hard ones",
        "A report exists", "Every query has a result-equal + cheaper verdict")),
  },
  {
    id: "doc-generation", loop: true, listName: "modules", item: "module",
    intent: "Generate API docs from each module; signatures match the actual code.",
    ground: "the source signatures",
    discover: discover("parse-modules",
      "Parse each module's real exported signatures into the grounding bundle.",
      hard("Real signatures captured", "sig-matches",
        "doc-gen with no parsed signatures (so docs could drift from code)",
        "A module list exists", "Each module's real signatures are on disk")),
    steps: [
      { id: "doc-module", does: "Generate docs for <module>.",
        gate: [
          hard("Documented signatures match the real code", "sig-matches",
            "documenting fn(a, b) when the code's signature is fn(a, b, c)",
            "Docs were generated",
            "Every documented function's params/return type match the parsed source signature"),
          soft("Docs are useful.",
            "Each function has a real description + example, not just a restated signature."),
        ]},
    ],
    finish: finish("parse-modules", "Confirm every module documented + accurate.",
      hard("All modules documented", "coverage-complete",
        "documenting the public API but skipping a whole module",
        "A docs file exists", "Every module has signature-accurate docs")),
  },
  {
    id: "sentiment-analysis", loop: true, listName: "reviews", item: "review",
    intent: "Score each review's sentiment; label matches the text and scale is valid.",
    ground: "the review text",
    discover: discover("load-reviews",
      "Load reviews + the sentiment scale definition into the grounding bundle.",
      hard("Reviews + scale loaded", "sentiment-grounded",
        "scoring with no scale on disk (so any number passes)",
        "A review list exists", "The scale + review texts are on disk")),
    steps: [
      { id: "score-review", does: "Score <review>.",
        gate: [
          hard("Score is on the valid scale", "scale-valid",
            "a score of 7 on a 1-5 scale",
            "A score exists",
            "The score is within the defined scale"),
          hard("Label is consistent with the review text", "sentiment-grounded",
            "labeling 'this was terrible, never again' as positive",
            "A label exists",
            "The label's polarity is consistent with the review text's actual sentiment cues"),
          soft("Scores are calibrated.",
            "Sarcasm/mixed reviews handled, not naively keyword-counted."),
        ]},
    ],
    finish: finish("load-reviews", "Confirm every review scored validly + grounded.",
      hard("All reviews scored", "coverage-complete",
        "scoring the English reviews, skipping the rest",
        "A scores file exists", "Every review has a valid, grounded score")),
  },
  {
    id: "video-transcription", loop: true, listName: "clips", item: "clip",
    intent: "Transcribe each clip; transcript aligns to audio and timestamps are monotonic.",
    ground: "the audio track",
    discover: discover("load-clips",
      "Load each clip's audio reference + duration into the grounding bundle.",
      hard("Audio refs + durations captured", "ts-monotonic",
        "transcribing with no duration baseline (timestamps unverifiable)",
        "A clip list exists", "Each clip's audio ref + duration are on disk")),
    steps: [
      { id: "transcribe-clip", does: "Transcribe <clip>.",
        gate: [
          hard("Timestamps are monotonic and within clip duration", "ts-monotonic",
            "a segment timestamped at 0:58 in a 0:45 clip, or timestamps going backwards",
            "A transcript exists",
            "Every segment timestamp is increasing and within the clip's real duration"),
          soft("Transcript is accurate.",
            "Speaker turns + audible words captured, not paraphrased or hallucinated over silence."),
        ]},
    ],
    finish: finish("load-clips", "Confirm every clip transcribed + aligned.",
      hard("All clips transcribed", "coverage-complete",
        "transcribing 3 of 20 clips",
        "A transcript file exists", "Every clip has an aligned transcript")),
  },
  {
    id: "price-monitoring", loop: true, listName: "products", item: "product",
    intent: "Record each product's current price from the live listing; flag real changes.",
    ground: "the live listing + the last recorded price",
    discover: discover("load-products",
      "Load products + their last recorded prices, and fetch each live listing into the grounding bundle.",
      hard("Live listings + last prices captured", "price-on-listing",
        "a product list with no live listing fetched (price unverifiable)",
        "A product list exists", "Each product's live listing + last price are on disk")),
    steps: [
      { id: "record-price", does: "Record <product>'s current price.",
        gate: [
          hard("Recorded price appears on the live listing", "price-on-listing",
            "recording 199 when the live listing shows 249 (stale/guessed)",
            "A price was recorded",
            "The recorded price string appears in the fetched live listing"),
          hard("Change flag matches the actual delta vs last price", "change-correct",
            "flagging 'no change' when the price actually dropped 20%",
            "A flag was set",
            "The change flag is consistent with (live price - last price)"),
          soft("Monitoring is robust.",
            "Out-of-stock / promo-price edge cases handled, not recorded as a real price drop."),
        ]},
    ],
    finish: finish("load-products", "Confirm every product priced from its live listing.",
      hard("All products checked", "coverage-complete",
        "checking 10 of 200 products",
        "A price log exists", "Every product has a listing-grounded price + correct flag")),
  },
  {
    id: "license-compliance", loop: true, listName: "packages", item: "package",
    intent: "Check each dependency's license against the allowlist; verdict matches the real license.",
    ground: "the package's actual license file + the allowlist",
    discover: discover("load-packages",
      "Load packages + the license allowlist; capture each package's real license text into the grounding bundle.",
      hard("Real license text + allowlist captured", "license-correct",
        "checking with no license text on disk (verdict ungrounded)",
        "A package list exists", "Each package's license text + the allowlist are on disk")),
    steps: [
      { id: "check-license", does: "Check <package>'s license.",
        gate: [
          hard("Detected license matches the package's real license file", "license-correct",
            "labeling a GPL-3.0 package as MIT",
            "A license was detected",
            "The detected license matches the package's actual license file content"),
          hard("Verdict is consistent with the allowlist", "verdict-consistent",
            "passing a copyleft license the allowlist forbids",
            "A verdict exists",
            "The pass/fail verdict matches whether the (correctly detected) license is on the allowlist"),
          soft("Edge cases handled.",
            "Dual-licensed / custom licenses flagged for human review, not force-classified."),
        ]},
    ],
    finish: finish("load-packages", "Confirm every package's license checked + correct verdict.",
      hard("All packages checked", "coverage-complete",
        "checking direct deps but skipping transitive ones",
        "A report exists", "Every package has a correct, allowlist-consistent verdict")),
  },
  {
    id: "backup-verification", loop: true, listName: "backups", item: "backup",
    intent: "Verify each backup is restorable and matches the source checksum.",
    ground: "a restore test + the source checksum",
    discover: discover("list-backups",
      "List backups; capture each backup's source checksum into the grounding bundle.",
      hard("Source checksums captured", "restore-matches",
        "verifying with no source checksum (so a corrupt restore could 'pass')",
        "A backup list exists", "Each backup's source checksum is on disk")),
    steps: [
      { id: "verify-backup", does: "Verify <backup>.",
        gate: [
          hard("Restored data checksum equals the source checksum", "restore-matches",
            "a backup that restores but whose checksum differs (silent corruption)",
            "A restore was attempted",
            "The restored data's checksum equals the recorded source checksum (a restorable-but-corrupt backup is a failed backup)"),
          soft("Verification is real.",
            "The restore was an actual restore test, not just a file-exists check."),
        ]},
    ],
    finish: finish("list-backups", "Confirm every backup restorable + matching.",
      hard("All backups verified", "coverage-complete",
        "verifying last night's backup only",
        "A report exists", "Every backup has a restore-matches verdict")),
  },
  {
    id: "form-data-entry", loop: true, listName: "forms", item: "form",
    intent: "Enter each form record into the system; stored values equal the source form.",
    ground: "the source form",
    discover: discover("load-forms",
      "Load source forms into the grounding bundle (the truth stored values are checked against).",
      hard("Source forms captured", "stored-matches",
        "data entry with no source form on disk (stored values unverifiable)",
        "A form list exists", "Each source form is on disk")),
    steps: [
      { id: "enter-form", does: "Enter <form> into the system.",
        gate: [
          hard("Stored values equal the source form (read-back)", "stored-matches",
            "a typo that stored '1990' for a birth year the form shows as '1980'",
            "An entry was submitted",
            "A read-back of the stored record equals the source form field-for-field (verify storage, not the submit call)"),
          soft("Entry is clean.",
            "Required fields all populated; no field left default/blank that the form filled."),
        ]},
    ],
    finish: finish("load-forms", "Confirm every form entered + read-back matches.",
      hard("All forms entered", "coverage-complete",
        "entering 40 of 60 forms",
        "An entry log exists", "Every form has a read-back-matches verdict")),
  },
  {
    id: "knowledge-base-update", loop: true, listName: "kb_articles", item: "kb",
    intent: "Update each KB article to current product reality; no stale claims remain.",
    ground: "the current product/code reality",
    discover: discover("load-kb",
      "Load KB articles + a snapshot of current product reality (features/flags/endpoints) into the grounding bundle.",
      hard("Current reality + articles captured", "no-stale-claims",
        "updating with no current-reality snapshot (so staleness can't be checked)",
        "A KB list exists", "Each article + the current-reality snapshot are on disk")),
    steps: [
      { id: "update-kb", does: "Update <kb>.",
        gate: [
          hard("No claim contradicts current product reality", "no-stale-claims",
            "leaving 'export is CSV-only' when the product now also exports JSON",
            "The article was edited",
            "Every factual claim in the updated article is consistent with the current-reality snapshot (no stale claim survives)"),
          soft("Update is genuinely improved.",
            "Examples + screenshots reflect the current UI, not just the prose."),
        ]},
    ],
    finish: finish("load-kb", "Confirm every article current, no stale claims.",
      hard("All articles updated", "coverage-complete",
        "updating the popular articles, skipping the long tail",
        "A report exists", "Every article has a no-stale-claims verdict")),
  },

  // ===================== 10 OBSCURE =====================
  {
    id: "tarot-spread", loop: true, listName: "positions", item: "position",
    intent: "Generate a spread reading where each position's meaning matches the drawn card's canonical meaning AND the position's defined role.",
    ground: "the canonical card-meaning reference + the spread layout definition",
    discover: discover("define-spread",
      "Load the spread layout (each position + its role, e.g. 'past', 'obstacle') and the canonical\ncard-meaning reference into the grounding bundle, and draw a card per position.",
      hard("Layout + meanings + draws captured", "meaning-grounded",
        "a reading with no canonical meanings on disk (so any interpretation passes)",
        "A position list exists", "The layout roles + canonical meanings + drawn cards are on disk")),
    steps: [
      { id: "interpret-position", does: "Interpret <position>.",
        gate: [
          hard("Interpretation matches the drawn card's canonical meaning", "meaning-grounded",
            "reading 'The Tower' (upheaval) as 'stable comfort' — contradicting its canonical meaning",
            "An interpretation was written",
            "The interpretation reflects the drawn card's canonical meaning (incl. reversed) — not a meaning invented for the card"),
          hard("Interpretation addresses this position's defined role", "role-addressed",
            "writing a generic blurb that never connects the card to this position's role ('past'/'advice')",
            "Text was produced",
            "The interpretation ties the card's meaning to THIS position's role, not a free-floating description"),
          soft("Reading is cohesive.",
            "Positions connect into one narrative arc, not 5 disconnected card descriptions."),
        ]},
    ],
    finish: finish("define-spread", "Confirm every position interpreted, grounded + role-tied.",
      hard("All positions read", "coverage-complete",
        "reading 3 of 5 positions and calling it a spread",
        "A reading file exists", "Every spread position has a grounded, role-tied interpretation")),
  },
  {
    id: "bonsai-judging", loop: true, listName: "entries", item: "entry",
    intent: "Score each bonsai entry on rubric criteria; scores reflect the entry's measured traits and sum correctly.",
    ground: "the entry's measured traits + the rubric weights",
    discover: discover("load-entries",
      "Load entries with their MEASURED traits (nebari spread, taper, ramification, pot harmony…) and the\nrubric (criteria + max points each) into the grounding bundle.",
      hard("Traits + rubric captured", "score-sums",
        "judging with no measured traits on disk (so scores are unfalsifiable)",
        "An entry list exists", "Each entry's measured traits + the rubric weights are on disk")),
    steps: [
      { id: "score-entry", does: "Score <entry>.",
        gate: [
          hard("Per-criterion scores sum to the reported total", "score-sums",
            "a total of 88 while the per-criterion scores sum to 79",
            "A total was given",
            "The reported total equals the sum of per-criterion scores, each within its rubric max"),
          hard("Each criterion score is justified by a measured trait", "score-grounded",
            "awarding full nebari points to an entry whose measured nebari is poor",
            "Scores were assigned",
            "Each criterion's score is consistent with the entry's measured trait for that criterion (no score contradicts the measurement)"),
          soft("Judging is fair.",
            "Comparable entries scored consistently; comments justify deductions a competitor could learn from."),
        ]},
    ],
    finish: finish("load-entries", "Confirm every entry scored, summed, grounded.",
      hard("All entries judged", "coverage-complete",
        "judging the favorites, skipping the rest",
        "A scoresheet exists", "Every entry has a summed, trait-grounded score")),
  },
  {
    id: "manuscript-transcription", loop: true, listName: "folios", item: "folio",
    intent: "Transcribe each folio; every expanded abbreviation and uncertain reading is marked and matches the imaged glyphs.",
    ground: "the folio image + the abbreviation reference",
    discover: discover("load-folios",
      "Load folio images + the scribal-abbreviation reference (sigla -> expansion) into the grounding bundle.",
      hard("Folio images + abbrev reference captured", "expansion-grounded",
        "transcribing with no abbreviation reference (so expansions are guesses)",
        "A folio list exists", "Each folio image + the abbreviation reference are on disk")),
    steps: [
      { id: "transcribe-folio", does: "Transcribe <folio>.",
        gate: [
          hard("Every abbreviation expansion matches the reference", "expansion-grounded",
            "silently expanding the Tironian et to 'and' inline with no mark, or expanding a sigla to a word the reference doesn't list",
            "A transcription exists",
            "Every expanded abbreviation is marked AND its expansion matches the abbreviation reference"),
          hard("Uncertain readings are explicitly flagged", "uncertainty-marked",
            "transcribing a damaged/illegible word as if it were a confident reading",
            "Text was produced",
            "Damaged/ambiguous glyphs are flagged (e.g. [?]) rather than silently resolved"),
          soft("Transcription is faithful.",
            "Line breaks, abbreviation density, and orthography reflect the actual folio, not normalized modern spelling."),
        ]},
    ],
    finish: finish("load-folios", "Confirm every folio transcribed, expansions + uncertainty marked.",
      hard("All folios transcribed", "coverage-complete",
        "transcribing the legible folios, skipping the damaged ones",
        "A transcription file exists", "Every folio has a grounded, uncertainty-marked transcription")),
  },
  {
    id: "fantasy-trade-eval", loop: true, listName: "trades", item: "trade",
    intent: "Evaluate each proposed trade for fairness using real player projections + league scoring rules.",
    ground: "the player projection table + the league scoring settings",
    discover: discover("load-league",
      "Load the player projection table + the league's scoring settings (PPR? categories?) into the grounding bundle,\nand collect the proposed trades.",
      hard("Projections + scoring rules captured", "value-grounded",
        "evaluating with no projections on disk (so 'fair' is vibes)",
        "A trade list exists", "The projection table + scoring settings are on disk")),
    steps: [
      { id: "eval-trade", does: "Evaluate <trade>.",
        gate: [
          hard("Each side's value uses real projections under the league's scoring", "value-grounded",
            "calling a trade fair using standard-scoring values in a PPR league (wrong ruleset)",
            "A verdict was given",
            "Each side's projected value is computed from the projection table UNDER this league's scoring settings (not generic rankings)"),
          hard("Fairness verdict is consistent with the computed value gap", "verdict-consistent",
            "declaring 'even trade' when one side is +40% in projected points",
            "A verdict string exists",
            "The fair/lopsided verdict matches the actual computed value differential"),
          soft("Eval is insightful.",
            "Positional scarcity, bye weeks, and roster fit are weighed, not just raw point totals."),
        ]},
    ],
    finish: finish("load-league", "Confirm every trade evaluated under real rules.",
      hard("All trades evaluated", "coverage-complete",
        "evaluating the interesting trades, skipping the rest",
        "A report exists", "Every trade has a projection-grounded, consistent verdict")),
  },
  {
    id: "perfume-blend", loop: true, listName: "blends", item: "blend",
    intent: "Formulate each blend so notes are balanced, IFRA limits respected, and percentages sum to 100.",
    ground: "the ingredient IFRA-limit table + the note-pyramid rules",
    discover: discover("load-ingredients",
      "Load the ingredient table (each with its IFRA max % and note class: top/heart/base) into the grounding bundle.",
      hard("Ingredient table + limits captured", "pct-sums",
        "formulating with no IFRA table on disk (so safety limits are unchecked)",
        "A blend list exists", "The ingredient table with IFRA limits + note classes is on disk")),
    steps: [
      { id: "formulate-blend", does: "Formulate <blend>.",
        gate: [
          hard("Ingredient percentages sum to 100", "pct-sums",
            "a formula whose percentages sum to 93",
            "A formula was written",
            "The ingredient percentages sum to exactly 100"),
          hard("No ingredient exceeds its IFRA limit", "ifra-respected",
            "using oakmoss at 5% when its IFRA limit is 0.1%",
            "Ingredients were chosen",
            "Every ingredient's percentage is at or below its IFRA limit from the table (a fragrance that violates IFRA is unsellable)"),
          soft("Blend is balanced.",
            "Top/heart/base proportions give a coherent evolution, not all-base or all-top."),
        ]},
    ],
    finish: finish("load-ingredients", "Confirm every blend sums + IFRA-compliant.",
      hard("All blends formulated", "coverage-complete",
        "formulating 2 of 6 blends",
        "A formula sheet exists", "Every blend sums to 100 + respects IFRA")),
  },
  {
    id: "birdsong-id", loop: true, listName: "recordings", item: "recording",
    intent: "Identify the species in each recording; ID is plausible for the region/season and cites acoustic features.",
    ground: "the spectrogram features + the regional species list",
    discover: discover("load-recordings",
      "Load recordings with their location/date + extracted acoustic features, and the regional species list\n(what's plausible here, this season) into the grounding bundle.",
      hard("Features + regional list captured", "id-in-region",
        "IDing with no regional species list (so any bird passes)",
        "A recording list exists", "Each recording's features + region/season + the regional species list are on disk")),
    steps: [
      { id: "id-recording", does: "Identify the species in <recording>.",
        gate: [
          hard("Identified species is plausible for the region+season", "id-in-region",
            "IDing a tropical species in a winter Scandinavian recording where it cannot occur",
            "A species was named",
            "The identified species is on the regional species list for this location+season (no geographically impossible ID)"),
          hard("ID cites acoustic features actually in the recording", "id-grounded",
            "citing a 'descending trill' the spectrogram features don't contain",
            "A rationale exists",
            "The cited acoustic features (pitch, rhythm, motif) are present in the recording's extracted features"),
          soft("ID is well-reasoned.",
            "Confusion species are ruled out by feature, not ignored."),
        ]},
    ],
    finish: finish("load-recordings", "Confirm every recording IDed, in-region + feature-grounded.",
      hard("All recordings IDed", "coverage-complete",
        "IDing the clear recordings, skipping the noisy ones",
        "A results file exists", "Every recording has an in-region, feature-grounded ID")),
  },
  {
    id: "tea-ceremony", loop: false,
    intent: "Produce a ceremony checklist where every step is in canonical order and uses utensils appropriate to the chosen style.",
    ground: "the canonical ceremony procedure for the chosen style",
    steps: [
      { id: "load-style", does: "Load the canonical procedure + utensil set for the chosen ceremony style into the grounding bundle.",
        gate: [ hard("Canonical procedure captured", "order-canonical",
          "writing the checklist with no canonical procedure on disk (order unverifiable)",
          "A procedure file exists", "The canonical step order + utensil set for the style are on disk") ]},
      { id: "build-checklist", does: "Build the ceremony checklist.",
        gate: [
          hard("Steps follow the canonical order", "order-canonical",
            "placing 'whisk the tea' before 'warm the bowl', violating the canonical sequence",
            "A checklist exists",
            "The checklist's step sequence matches the canonical order for this style (no transposed/missing core step)"),
          hard("Every utensil named is appropriate to the style", "utensil-valid",
            "calling for a utensil from a different ceremony tradition entirely",
            "Utensils were listed",
            "Every utensil named belongs to this style's defined utensil set"),
          soft("Checklist is usable.",
            "Timing/temperature cues are practical for a real practitioner, not just step names."),
        ]},
    ],
  },
  {
    id: "escape-room-puzzle", loop: true, listName: "puzzles", item: "puzzle",
    intent: "Design each puzzle so it is solvable from provided clues alone, has exactly one solution, and chains to the next.",
    ground: "the clue set + a solution-uniqueness check",
    discover: discover("plan-puzzles",
      "Plan the puzzle chain; for each puzzle capture its provided clue set + intended solution into the grounding bundle.",
      hard("Clue sets + solutions captured", "solvable-from-clues",
        "designing with no clue set on disk (so solvability is unverifiable)",
        "A puzzle list exists", "Each puzzle's clue set + intended solution are on disk")),
    steps: [
      { id: "design-puzzle", does: "Design <puzzle>.",
        gate: [
          hard("Puzzle is solvable from its provided clues alone", "solvable-from-clues",
            "a puzzle whose solution needs a fact never given in any clue (unsolvable / requires outside knowledge)",
            "A puzzle was written",
            "The intended solution is derivable from the provided clue set alone (no missing-clue dead end)"),
          hard("Exactly one solution (no ambiguity)", "unique-solution",
            "a cipher that two different inputs both satisfy, giving two valid 'answers'",
            "A solution exists",
            "Only the intended solution satisfies the clues — no second input also solves it"),
          soft("Puzzle is fun + chains well.",
            "Difficulty fits its place in the chain, and its output feeds the next puzzle cleanly."),
        ]},
    ],
    finish: finish("plan-puzzles", "Confirm every puzzle solvable, unique, chained.",
      hard("All puzzles designed", "coverage-complete",
        "designing the first 2 puzzles and stubbing the rest",
        "A puzzle pack exists", "Every puzzle is solvable-from-clues + has a unique solution")),
  },
  {
    id: "dialect-transcription", loop: true, listName: "recordings", item: "recording",
    intent: "Transcribe each dialect recording with IPA + orthography preserving non-standard features faithfully.",
    ground: "the audio + the dialect feature inventory",
    discover: discover("load-dialect",
      "Load recordings + the dialect feature inventory (the non-standard phonological/lexical markers to preserve)\ninto the grounding bundle.",
      hard("Audio + feature inventory captured", "features-preserved",
        "transcribing with no feature inventory (so standardization can't be caught)",
        "A recording list exists", "Each recording + the dialect feature inventory are on disk")),
    steps: [
      { id: "transcribe-dialect", does: "Transcribe <recording>.",
        gate: [
          hard("Non-standard dialect features are preserved, not normalized", "features-preserved",
            "transcribing the dialect into standard-language orthography, erasing the very features being documented",
            "A transcript exists",
            "The dialect features present in the audio (per the inventory) appear in the transcript — not silently standardized away"),
          hard("IPA is valid where used", "ipa-valid",
            "an IPA string with characters outside the IPA set",
            "IPA was produced",
            "Every IPA segment uses valid IPA symbols"),
          soft("Transcription is faithful.",
            "Prosody/hesitation conventions applied consistently, useful to a linguist."),
        ]},
    ],
    finish: finish("load-dialect", "Confirm every recording transcribed, features preserved.",
      hard("All recordings transcribed", "coverage-complete",
        "transcribing the clear speakers, skipping the heavy-dialect ones",
        "A transcript file exists", "Every recording has a feature-preserving transcript")),
  },
  {
    id: "heraldry-blazon", loop: true, listName: "blazons", item: "blazon",
    intent: "Validate each blazon: tincture rule (no colour-on-colour), grammar, and that it renders to the intended arms.",
    ground: "the heraldic grammar rules + the reference emblazon",
    discover: discover("load-blazons",
      "Load the blazons + the heraldic grammar rules (tincture classes, ordinary vocabulary) + each intended\nreference emblazon into the grounding bundle.",
      hard("Blazons + rules + references captured", "tincture-rule",
        "validating with no grammar rules on disk (so any string passes)",
        "A blazon list exists", "The grammar rules + reference emblazons are on disk")),
    steps: [
      { id: "validate-blazon", does: "Validate <blazon>.",
        gate: [
          hard("Tincture rule respected (no colour-on-colour / metal-on-metal)", "tincture-rule",
            "a blazon placing azure (colour) on gules (colour), violating the rule of tincture",
            "The blazon parses",
            "No charge places colour-on-colour or metal-on-metal (the core rule of tincture), per the tincture classes in the rules"),
          hard("Blazon grammar is valid (parses to a real emblazon)", "grammar-valid",
            "a blazon using an ordinary/term not in the heraldic vocabulary, so it can't render",
            "Text exists",
            "The blazon uses valid heraldic grammar/vocabulary and resolves to the intended reference emblazon"),
          soft("Blazon is well-formed.",
            "Ordering (field, then charges, then ordinaries) and marshalling conventions are idiomatic, not just legal."),
        ]},
    ],
    finish: finish("load-blazons", "Confirm every blazon valid + tincture-compliant.",
      hard("All blazons validated", "coverage-complete",
        "validating the simple blazons, skipping the quartered ones",
        "A report exists", "Every blazon has a tincture + grammar verdict")),
  },
];
